language: generic

notifications:
  email: false

services:
  - docker

jobs:
  include:
    - name: build
      before_install:
        - ./scripts/docker_build_image.sh

      script:
        - ./scripts/docker_run_container.sh
        - ./scripts/check_tests.sh

