language: generic

services:
  - docker

jobs:
  include:
    - name: build target
      before_install:
        - ./docker_run.sh
      script:
        - ./check_build.sh
        

#    - name: test
#      before_script:
#        - gcc --version
#      script:
#        - cd ${TRAVIS_BUILD_DIR}
#        - make test
#        - bash <(curl -s https://codecov.io/bash)